### ISSUE TITLE
Implement click on items

### ISSUE THREAD

**Issue by way2muchnoise** [way2muchnoise/JEIExporter#8]
Maybe R and U when hovering (if possible)?

**Comment by way2muchnoise** [comment]
Basic impl added in 76b500b19d20b48e81611231f69a45273b0829e4

**Comment by mezz** [comment]
Clicking planks only gives "uses" and not the "recipes".

**Comment by way2muchnoise** [comment]
Incorrect search related to #10 (the new way is not really working well)

**Comment by way2muchnoise** [comment]
I should show both "uses" and "recipes" on click now.
